// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/invoice/:id": {
    params: {
      "id": string;
    };
  };
  "/product/:id": {
    params: {
      "id": string;
    };
  };
  "/lacak/:awb": {
    params: {
      "awb": string;
    };
  };
  "/checkout": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/orders/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/invoice/:id" | "/product/:id" | "/lacak/:awb" | "/checkout" | "/admin" | "/admin/orders/:id";
  };
  "routes/invoice.$id.tsx": {
    id: "routes/invoice.$id";
    page: "/invoice/:id";
  };
  "routes/product.$id.tsx": {
    id: "routes/product.$id";
    page: "/product/:id";
  };
  "routes/lacak.$awb.tsx": {
    id: "routes/lacak.$awb";
    page: "/lacak/:awb";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/orders/:id";
  };
  "routes/admin.orders.$id.tsx": {
    id: "routes/admin.orders.$id";
    page: "/admin/orders/:id";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
};